### ISSUE TITLE
Error in Chrome console: [Vue warn]: Cannot find element: .v-cuztom

### ISSUE THREAD

**Issue by vellkan** [gizburdt/cuztom#375] opened 2017-03-06 14:59 UTC
Hello!

In Wordpress 4.7.2 fresh installation I've got this kind of error:
[Vue warn]: Cannot find element: .v-cuztom
Error shows this file: cuztom.min.js?ver=3.0:1141
and the line: console.error('[Vue warn]: ' + msg + (vm ? formatComponentName(vm) : ''));

It's connect with Visual Editor and problem with Media Library in post edition.

**Comment by gizburdt** [comment] 2017-03-06 15:02
Did you create a metabox with fields? If so, please post your code here :)

**Comment by vellkan** [comment] 2017-03-06 15:20
Yes.
I've try to create a bundle, but it didn't work, so I create this code:

$box = register_cuztom_meta_box( 'products_gallery', 'products', array(
  'title'   => 'Galeria zdjęć',
  'fields' => array(
    array(
      'id'            => '_data_image_1',
      'type'          => 'image',
      'label'         => 'Zdjęcie nr 1',
    ),
    array(
      'id'            => '_data_image_2',
      'type'          => 'image',
      'label'         => 'Zdjęcie nr 2',
    )
  )
));

**Comment by gizburdt** [comment] 2017-03-06 15:21
I will have a look at it

**Comment by vellkan** [comment] 2017-03-06 15:22
Great, thank You.
I love this solution for CPT :)

**Comment by gizburdt** [comment] 2017-03-06 15:29
Can you also give me the code where you register the post type?

**Comment by vellkan** [comment] 2017-03-06 15:30
$products = register_cuztom_post_type('products', array(
  'labels' => array(
    'name'                => __( 'Produkty' ),
    'singular_name'       => __( 'Produkty' ),
    'singular_label'      => __('Produkty'),
    'add_new'             => __( 'Dodaj produkt' ),
    'add_new_item'        => __( 'Dodaj produkt' ),
    'edit'                => __( 'Edytuj' ),
    'edit_item'           => __( 'Edytuj produkt' ),
    'new_item'            => __( 'Nowe produkt' ),
    'view'                => __( 'Zobacz produkt' ),
    'view_item'           => __( 'Zobacz produkt' ),
    'search_items'        => __( 'Znajdź produkt' ),
    'not_found'           => __( 'Nie znaleziono pasujących wpisów. Spróbuj ponownie.' ),
    'not_found_in_trash'  => __( 'Nie znaleziono pasujących wpisów. Spróbuj ponownie.' ),

    ),
  'public'                => true,
  'show_ui'               => true,
  'capability_type'       => 'post',
  'has_archive'           => true,
  'rewrite'               => array( 'slug' => 'products' ),
  'supports'              => array( 'title', 'editor', 'thumbnail' )
  ));

$genre = register_cuztom_taxonomy(
  'products_category',
  'products',
  array(
    'show_admin_column' => true,
    'admin_column_sortable' => true,
    'admin_column_filter' => true
    )
  );

**Comment by gizburdt** [comment] 2017-03-06 15:35
I can't reproduce this issue. 

<img width="905" alt="schermafbeelding 2017-03-06 om 16 34 10" src="https://cloud.githubusercontent.com/assets/1470623/23616662/d0e98c3e-028a-11e7-9201-0c850468ec8d.png">

Can you check with inspect element, if the element in the blue line is present?

**Comment by vellkan** [comment] 2017-03-06 15:39
But this error show only when I check & edit normal post or page, on CPT pages everything is OK.

**Comment by gizburdt** [comment] 2017-03-06 15:43
Ah ok! Sorry, didn't understand that. Thanks :)

**Comment by gizburdt** [comment] 2017-03-06 19:02
Should be fixed in 3.0.1 :)

**Comment by vellkan** [comment] 2017-03-06 19:49
Great, but now it's problem with AJAX in Admin Panel.
For example - I can't slide down Screen Options from top link.

**Comment by gizburdt** [comment] 2017-03-06 19:58
Is this problem on a certain screen?

**Comment by vellkan** [comment] 2017-03-06 20:00
On every screen where is this link - Posts, Menu editor, Category edit.

**Comment by vellkan** [comment] 2017-03-06 20:46
Next problem - it's generate problem with create photo gallery - after setup everything that don't put code in editor.

**Comment by gizburdt** [comment] 2017-03-06 21:23
Fixed. Was a conflict with bootstrap code. Thanks for the reports :)

**Comment by gizburdt** [comment] 2017-03-06 21:24
If you have other issues, please report them and create a new issue :)

**Closed by gizburdt** 2017-03-06 21:23 UTC
Labels: bug
